import { LevelDef, Emitter, Prism } from './types';
import { v2 } from './math';

// =========================================================================
// 🦄 TITLE SCENE CONFIGURATION
// All coordinates are within virtual 1000 × 1000 canvas space (center 500, 500):
// =========================================================================
export const TITLE_SCENE: { emitters: Emitter[]; prisms: Prism[] } = {
  emitters: [
    {
      pos: v2(80, 260),      // Left emitter position [X, Y]
      angle: 0.22,           // Beam angle in radians (aimed down-right)
      width: 7,              // Beam width
      rayCount: 128,          // Spectrum ray density
      minLambda: 400,        // 400 nm (violet)
      maxLambda: 700,        // 700 nm (red)
    },
    {
      pos: v2(920, 260),     // Right emitter position [X, Y]
      angle: 3,              // Beam angle in radians (aimed up-left)
      width: 7,
      rayCount: 128,
      minLambda: 400,
      maxLambda: 700,
    },
  ],
  prisms: [
    {
      id: 1,
      pos: v2(200, 300),     // Left unicorn position [X, Y]
      rot: 0,                // Default horn rotation in radians
      scale: 1,              // Scale multiplier
      baseIndex: 1.52,       // Refractive index of crystal
      dispersionB: 28000,    // Cauchy dispersion coefficient
      shape: 'horn',
      basePos: v2(200, 300), // Base anchor position for harmonic sway
      baseRot: 0.1,          // Base rotation for harmonic sway
      swayPhase: 0,          // Sway phase offset
    },
    {
      id: 2,
      pos: v2(800, 300),     // Right unicorn position [X, Y]
      rot: 0,                // Default horn rotation in radians
      scale: 1,              // Scale multiplier
      baseIndex: 1.52,       // Refractive index of crystal
      dispersionB: 28000,    // Cauchy dispersion coefficient
      shape: 'horn',
      basePos: v2(800, 300), // Base anchor position for harmonic sway
      baseRot: 0,            // Base rotation for harmonic sway
      swayPhase: Math.PI,    // Counter-phase sway
    },
  ],
};

export const LEVELS: LevelDef[] = [
  {
    id: 1,
    title: '1. The First Horn',
    subtitle: 'Double refraction: bending light with crystal power',
    hint: 'Isaac Newton who? Rotate your horn to bend the emerald beam into the sensor.',
    emitter: {
      pos: v2(90, 420),
      angle: 0,
      width: 7,
      rayCount: 64,
      minLambda: 400,
      maxLambda: 700,
    },
    prisms: [
      {
        id: 1,
        pos: v2(440, 420),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.5,
        dispersionB: 22000,
        shape: 'horn',
      },
    ],
    targets: [
      {
        id: 1,
        pos: v2(870, 660),
        radius: 25,
        minLambda: 520,
        maxLambda: 565,
        charge: 0,
        isSatisfied: false,
        name: 'Green Sensor',
      },
    ],
    obstacles: [],
  },
  {
    id: 2,
    title: '2. Rainbow Dispersion',
    subtitle: 'Cauchy dispersion: why rainbows are basically physics showing off',
    hint: 'Red bends gently, violet takes the sharpest dive. Fan out the spectrum downward to hit all three!',
    emitter: {
      pos: v2(90, 300),
      angle: 0,
      width: 7,
      rayCount: 68,
      minLambda: 400,
      maxLambda: 700,
    },
    prisms: [
      {
        id: 1,
        pos: v2(340, 300),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.52,
        dispersionB: 32000,
        shape: 'horn',
      },
    ],
    targets: [
      {
        id: 1,
        pos: v2(880, 620),
        radius: 24,
        minLambda: 630,
        maxLambda: 700,
        charge: 0,
        isSatisfied: false,
        name: 'Red Sensor',
      },
      {
        id: 2,
        pos: v2(880, 660),
        radius: 24,
        minLambda: 520,
        maxLambda: 565,
        charge: 0,
        isSatisfied: false,
        name: 'Green Sensor',
      },
      {
        id: 3,
        pos: v2(880, 780),
        radius: 24,
        minLambda: 400,
        maxLambda: 450,
        charge: 0,
        isSatisfied: false,
        name: 'Violet Sensor',
      },
    ],
    obstacles: [],
  },
  {
    id: 3,
    title: '3. The Obsidian Shield',
    subtitle: 'Upward refraction: slipping under the barrier',
    hint: 'The sensor is tucked behind a heavy shield. Turn your horn upside down to bend light upward into the pocket!',
    emitter: {
      pos: v2(90, 820),
      angle: 0,
      width: 7,
      rayCount: 64,
      minLambda: 400,
      maxLambda: 700,
    },
    prisms: [
      {
        id: 1,
        pos: v2(420, 820),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.5,
        dispersionB: 22000,
        shape: 'horn',
      },
    ],
    targets: [
      {
        id: 1,
        pos: v2(880, 590),
        radius: 25,
        minLambda: 520,
        maxLambda: 565,
        charge: 0,
        isSatisfied: false,
        name: 'Green Sensor',
      },
    ],
    obstacles: [
      {
        id: 1,
        points: [v2(770, 50), v2(810, 50), v2(810, 620), v2(770, 620)],
      },
    ],
  },
  {
    id: 4,
    title: '4. Total Internal Reflection',
    subtitle: 'Critical angles: when crystal turns into a mirror',
    hint: 'Refraction alone cannot make this sharp 90° turn. Rotate into a steep angle for internal reflection!',
    emitter: {
      pos: v2(90, 240),
      angle: 0,
      width: 7,
      rayCount: 64,
      minLambda: 400,
      maxLambda: 700,
    },
    prisms: [
      {
        id: 1,
        pos: v2(340, 240),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.56,
        dispersionB: 15000,
        shape: 'horn',
      },
      {
        id: 2,
        pos: v2(340, 750),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.56,
        dispersionB: 15000,
        shape: 'horn',
      },
    ],
    targets: [
      {
        id: 1,
        pos: v2(880, 780),
        radius: 28,
        minLambda: 400,
        maxLambda: 480,
        charge: 0,
        isSatisfied: false,
        name: 'Blue Sensor',
      },
    ],
    obstacles: [
      {
        id: 1,
        points: [v2(480, 50), v2(520, 50), v2(520, 650), v2(480, 650)],
      },
    ],
  },
  {
    id: 5,
    title: '5. Twin Horn Relay',
    subtitle: 'Pass the photon: multi-stage crystal cascade',
    hint: 'First horn bends the beam downward under wall 1, second horn catches it and sends it over wall 2!',
    emitter: {
      pos: v2(90, 240),
      angle: 0,
      width: 7,
      rayCount: 64,
      minLambda: 400,
      maxLambda: 700,
    },
    prisms: [
      {
        id: 1,
        pos: v2(220, 240),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.5,
        dispersionB: 20000,
        shape: 'horn',
      },
      {
        id: 2,
        pos: v2(520, 410),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.5,
        dispersionB: 20000,
        shape: 'horn',
      },
    ],
    targets: [
      {
        id: 1,
        pos: v2(880, 420),
        radius: 25,
        minLambda: 620,
        maxLambda: 685,
        charge: 0,
        isSatisfied: false,
        name: 'Red Sensor',
      },
      {
        id: 2,
        pos: v2(880, 465),
        radius: 25,
        minLambda: 420,
        maxLambda: 485,
        charge: 0,
        isSatisfied: false,
        name: 'Blue Sensor',
      },
    ],
    obstacles: [
      {
        id: 1,
        points: [v2(360, 50), v2(400, 50), v2(400, 290), v2(360, 290)],
      },
      {
        id: 2,
        points: [v2(660, 470), v2(700, 470), v2(700, 950), v2(660, 950)],
      },
    ],
  },
  {
    id: 6,
    title: '6. The Celestial Mirror',
    subtitle: 'Specular reflection: keep your beam intact',
    hint: 'Mirrors don\'t split rainbows—they bounce the whole white beam like a champ.',
    emitter: {
      pos: v2(90, 750),
      angle: -1.27,
      width: 7,
      rayCount: 64,
      minLambda: 400,
      maxLambda: 700,
    },
    prisms: [
      {
        id: 1,
        pos: v2(260, 200),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.0,
        dispersionB: 0,
        shape: 'mirror',
      },
      {
        id: 2,
        pos: v2(640, 200),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.52,
        dispersionB: 26000,
        shape: 'horn',
      },
    ],
    targets: [
      {
        id: 1,
        pos: v2(880, 328),
        radius: 24,
        minLambda: 620,
        maxLambda: 685,
        charge: 0,
        isSatisfied: false,
        name: 'Red Sensor',
      },
      {
        id: 2,
        pos: v2(880, 368),
        radius: 24,
        minLambda: 420,
        maxLambda: 485,
        charge: 0,
        isSatisfied: false,
        name: 'Blue Sensor',
      },
    ],
    obstacles: [
      {
        id: 1,
        points: [v2(480, 420), v2(520, 420), v2(520, 950), v2(480, 950)],
      },
    ],
  },
  {
    id: 7,
    title: '7. Chrome & Obsidian',
    subtitle: 'Bank shots in deep space: fixed mirrors meet moving horns',
    hint: 'Bounce the beam off the polished chrome wall before running it through the prism.',
    emitter: {
      pos: v2(90, 220),
      angle: 1.05,
      width: 7,
      rayCount: 64,
      minLambda: 400,
      maxLambda: 700,
    },
    prisms: [
      {
        id: 1,
        pos: v2(600, 570),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.52,
        dispersionB: 26000,
        shape: 'horn',
      },
    ],
    targets: [
      {
        id: 1,
        pos: v2(880, 384),
        radius: 24,
        minLambda: 620,
        maxLambda: 700,
        charge: 0,
        isSatisfied: false,
        name: 'Red Sensor',
      },
      {
        id: 2,
        pos: v2(880, 422),
        radius: 24,
        minLambda: 400,
        maxLambda: 480,
        charge: 0,
        isSatisfied: false,
        name: 'Cyan Sensor',
      },
    ],
    obstacles: [
      {
        id: 1,
        points: [v2(350, 50), v2(400, 50), v2(400, 480), v2(350, 480)],
      },
      {
        id: 2,
        points: [v2(260, 840), v2(580, 840), v2(580, 860), v2(260, 860)],
        isMirror: true,
      },
      {
        id: 3,
        points: [v2(680, 580), v2(730, 580), v2(730, 950), v2(680, 950)],
      },
    ],
  },
  {
    id: 8,
    title: '8. Additive Alchemy: Yellow',
    subtitle: 'RGB synthesis: Red + Green = Golden Glow',
    hint: 'Single colors won\'t satisfy this sensor. Intersect both beams right inside its lens!',
    emitter: [
      {
        pos: v2(90, 240),
        angle: 0,
        width: 7,
        rayCount: 52,
        minLambda: 650,
        maxLambda: 680,
      },
      {
        pos: v2(90, 760),
        angle: 0,
        width: 7,
        rayCount: 52,
        minLambda: 525,
        maxLambda: 545,
      },
    ],
    prisms: [
      {
        id: 1,
        pos: v2(380, 240),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.52,
        dispersionB: 12000,
        shape: 'horn',
      },
      {
        id: 2,
        pos: v2(380, 760),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.52,
        dispersionB: 12000,
        shape: 'horn',
      },
    ],
    targets: [
      {
        id: 1,
        pos: v2(870, 500),
        radius: 26,
        minLambda: 520,
        maxLambda: 680,
        targetRgb: [255, 235, 0],
        charge: 0,
        isSatisfied: false,
        name: 'Yellow Sensor',
      },
    ],
    obstacles: [
      {
        id: 1,
        points: [v2(520, 360), v2(560, 360), v2(560, 640), v2(520, 640)],
      },
    ],
  },
  {
    id: 9,
    title: '9. Dual Synthesis: Cyan & Magenta',
    subtitle: 'Secondary harmonics: mixing Green, Blue, and Red',
    hint: 'Blue is in high demand! Mix Blue with Green for Cyan, and Blue with Red for radiant Magenta.',
    emitter: [
      {
        pos: v2(90, 240),
        angle: 0,
        width: 6,
        rayCount: 48,
        minLambda: 650,
        maxLambda: 680,
      },
      {
        pos: v2(90, 500),
        angle: 0,
        width: 14,
        rayCount: 64,
        minLambda: 440,
        maxLambda: 470,
      },
      {
        pos: v2(90, 760),
        angle: 0,
        width: 6,
        rayCount: 48,
        minLambda: 525,
        maxLambda: 545,
      },
    ],
    prisms: [
      {
        id: 1,
        pos: v2(240, 240),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.5,
        dispersionB: 8000,
        shape: 'horn',
      },
      {
        id: 2,
        pos: v2(240, 760),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.5,
        dispersionB: 8000,
        shape: 'horn',
      },
      {
        id: 3,
        pos: v2(360, 500),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.52,
        dispersionB: 24000,
        shape: 'horn',
      },
    ],
    targets: [
      {
        id: 1,
        pos: v2(880, 550),
        radius: 26,
        targetRgb: [255, 60, 220],
        minLambda: 400,
        maxLambda: 700,
        charge: 0,
        isSatisfied: false,
        name: 'Magenta Sensor',
      },
      {
        id: 2,
        pos: v2(880, 480),
        radius: 26,
        targetRgb: [0, 240, 255],
        minLambda: 400,
        maxLambda: 700,
        charge: 0,
        isSatisfied: false,
        name: 'Cyan Sensor',
      },
    ],
    obstacles: [],
  },
  {
    id: 10,
    title: '10. Recombining White',
    subtitle: 'Newton\'s reverse trick: putting the rainbow back together',
    hint: 'Individual spectral colors are too saturated. Converge the whole rainbow back into pure white.',
    emitter: {
      pos: v2(90, 500),
      angle: 0,
      width: 6,
      rayCount: 68,
      minLambda: 400,
      maxLambda: 700,
    },
    prisms: [
      {
        id: 1,
        pos: v2(280, 520),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.52,
        dispersionB: 26000,
        shape: 'horn',
      },
      {
        id: 2,
        pos: v2(600, 560),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.52,
        dispersionB: 26000,
        shape: 'horn',
      },
    ],
    targets: [
      {
        id: 1,
        pos: v2(880, 500),
        radius: 28,
        targetRgb: [255, 255, 255],
        minLambda: 400,
        maxLambda: 700,
        charge: 0,
        isSatisfied: false,
        name: 'White Sensor',
      },
    ],
    obstacles: [
      {
        id: 1,
        points: [v2(420, 460), v2(460, 460), v2(460, 540), v2(420, 540)],
      },
    ],
  },
  {
    id: 11,
    title: '11. Inverted Spectrum: The Dove Prism',
    subtitle: 'Image inversion: flipping rainbows upside-down',
    hint: 'The colors are in the wrong order! Run them through the Dove prism to flip the spectrum.',
    emitter: {
      pos: v2(90, 500),
      angle: 0,
      width: 6,
      rayCount: 68,
      minLambda: 400,
      maxLambda: 700,
    },
    prisms: [
      {
        id: 1,
        pos: v2(260, 500),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.52,
        dispersionB: 26000,
        shape: 'horn',
      },
      {
        id: 2,
        pos: v2(540, 680),
        rot: 0.12,
        scale: 1.1,
        baseIndex: 1.53,
        dispersionB: 12000,
        shape: 'dove',
      },
    ],
    targets: [
      {
        id: 1,
        pos: v2(880, 570),
        radius: 25,
        minLambda: 430,
        maxLambda: 485,
        charge: 0,
        isSatisfied: false,
        name: 'Blue Sensor',
      },
      {
        id: 2,
        pos: v2(880, 898),
        radius: 25,
        minLambda: 620,
        maxLambda: 700,
        charge: 0,
        isSatisfied: false,
        name: 'Red Sensor',
      },
    ],
    obstacles: [
      {
        id: 1,
        points: [v2(420, 50), v2(460, 50), v2(460, 540), v2(420, 540)],
      },
    ],
  },
  {
    id: 12,
    title: '12. The Crystal Orb: Focusing Lens',
    subtitle: 'Spherical refraction: harnessing the crystal lens',
    hint: 'A spread-out beam is too weak. Focus it into a blazing pinpoint with the crystal orb.',
    emitter: {
      pos: v2(90, 500),
      angle: 0,
      width: 28,
      rayCount: 76,
      minLambda: 520,
      maxLambda: 565,
    },
    prisms: [
      {
        id: 1,
        pos: v2(420, 500),
        rot: 0,
        scale: 1.25,
        baseIndex: 1.58,
        dispersionB: 18000,
        shape: 'orb',
      },
    ],
    targets: [
      {
        id: 1,
        pos: v2(880, 500),
        radius: 20,
        minLambda: 520,
        maxLambda: 565,
        charge: 0,
        isSatisfied: false,
        name: 'Green Sensor',
      },
    ],
    obstacles: [
      {
        id: 1,
        points: [v2(740, 50), v2(780, 50), v2(780, 475), v2(740, 475)],
      },
      {
        id: 2,
        points: [v2(740, 525), v2(780, 525), v2(780, 950), v2(740, 950)],
      },
    ],
  },
  {
    id: 13,
    title: '13. The Caustic Keyhole',
    subtitle: 'Through the needle\'s eye: precision focal alignment',
    hint: 'The gap in the wall is razor-thin. Focus all rays into a single point right inside the opening!',
    emitter: {
      pos: v2(90, 500),
      angle: 0,
      width: 8,
      rayCount: 72,
      minLambda: 400,
      maxLambda: 700,
    },
    prisms: [
      {
        id: 1,
        pos: v2(320, 500),
        rot: 0,
        scale: 1.15,
        baseIndex: 1.56,
        dispersionB: 22000,
        shape: 'orb',
      },
      {
        id: 2,
        pos: v2(660, 500),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.52,
        dispersionB: 28000,
        shape: 'horn',
      },
    ],
    targets: [
      {
        id: 1,
        pos: v2(880, 586),
        radius: 24,
        minLambda: 620,
        maxLambda: 690,
        charge: 0,
        isSatisfied: false,
        name: 'Red Sensor',
      },
      {
        id: 2,
        pos: v2(880, 438),
        radius: 24,
        minLambda: 420,
        maxLambda: 485,
        charge: 0,
        isSatisfied: false,
        name: 'Blue Sensor',
      },
    ],
    obstacles: [
      {
        id: 1,
        points: [v2(480, 50), v2(520, 50), v2(520, 485), v2(480, 485)],
      },
      {
        id: 2,
        points: [v2(480, 515), v2(520, 515), v2(520, 950), v2(480, 950)],
      },
    ],
  },
  {
    id: 14,
    title: '14. The Crystal Labyrinth',
    subtitle: 'Chamber of reflections: multi-room optical routing',
    hint: 'Route the primary beam through the labyrinth using your mirror, then let the horns split the colors.',
    emitter: {
      pos: v2(90, 240),
      angle: 0,
      width: 7,
      rayCount: 68,
      minLambda: 400,
      maxLambda: 700,
    },
    prisms: [
      {
        id: 1,
        pos: v2(272, 240),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.0,
        dispersionB: 0,
        shape: 'mirror',
      },
      {
        id: 2,
        pos: v2(272, 750),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.5,
        dispersionB: 15000,
        shape: 'horn',
      },
      {
        id: 3,
        pos: v2(560, 760),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.52,
        dispersionB: 32000,
        shape: 'horn',
      },
    ],
    targets: [
      {
        id: 1,
        pos: v2(880, 505),
        radius: 24,
        minLambda: 400,
        maxLambda: 460,
        charge: 0,
        isSatisfied: false,
        name: 'Blue Sensor',
      },
      {
        id: 2,
        pos: v2(880, 542),
        radius: 24,
        minLambda: 520,
        maxLambda: 570,
        charge: 0,
        isSatisfied: false,
        name: 'Green Sensor',
      },
      {
        id: 3,
        pos: v2(880, 558),
        radius: 24,
        minLambda: 620,
        maxLambda: 700,
        charge: 0,
        isSatisfied: false,
        name: 'Red Sensor',
      },
    ],
    obstacles: [
      {
        id: 1,
        points: [v2(380, 50), v2(420, 50), v2(420, 600), v2(380, 600)],
      },
      {
        id: 2,
        points: [v2(640, 780), v2(680, 780), v2(680, 950), v2(640, 950)],
      },
    ],
  },
  {
    id: 15,
    title: '15. The Grand Optical Symphony',
    subtitle: 'Master of photons: the ultimate celestial harmony',
    hint: 'Your entire optical toolkit is unlocked. Orchestrate all four artifacts to illuminate every sensor!',
    emitter: [
      {
        pos: v2(90, 240),
        angle: 0,
        width: 7,
        rayCount: 48,
        minLambda: 400,
        maxLambda: 700,
      },
      {
        pos: v2(90, 500),
        angle: 0,
        width: 24,
        rayCount: 64,
        minLambda: 520,
        maxLambda: 565,
      },
      {
        pos: v2(90, 760),
        angle: 0,
        width: 7,
        rayCount: 48,
        minLambda: 400,
        maxLambda: 700,
      },
    ],
    prisms: [
      {
        id: 1,
        pos: v2(340, 240),
        rot: 0.05,
        scale: 1.0,
        baseIndex: 1.52,
        dispersionB: 28000,
        shape: 'horn',
      },
      {
        id: 2,
        pos: v2(500, 500),
        rot: 0,
        scale: 1.25,
        baseIndex: 1.58,
        dispersionB: 18000,
        shape: 'orb',
      },
      {
        id: 3,
        pos: v2(340, 760),
        rot: 0.05,
        scale: 1.1,
        baseIndex: 1.53,
        dispersionB: 12000,
        shape: 'dove',
      },
      {
        id: 4,
        pos: v2(540, 880),
        rot: 0.05,
        scale: 1.5,
        baseIndex: 1.0,
        dispersionB: 0,
        shape: 'mirror',
      },
    ],
    targets: [
      {
        id: 1,
        pos: v2(880, 555),
        radius: 24,
        minLambda: 620,
        maxLambda: 690,
        charge: 0,
        isSatisfied: false,
        name: 'Red Sensor',
      },
      {
        id: 2,
        pos: v2(880, 580),
        radius: 24,
        minLambda: 540,
        maxLambda: 610,
        charge: 0,
        isSatisfied: false,
        name: 'Gold Sensor',
      },
      {
        id: 3,
        pos: v2(880, 500),
        radius: 22,
        minLambda: 520,
        maxLambda: 565,
        charge: 0,
        isSatisfied: false,
        name: 'Green Sensor',
      },
      {
        id: 4,
        pos: v2(880, 563),
        radius: 24,
        minLambda: 560,
        maxLambda: 620,
        charge: 0,
        isSatisfied: false,
        name: 'Cyan Sensor',
      },
      {
        id: 5,
        pos: v2(880, 574),
        radius: 24,
        minLambda: 650,
        maxLambda: 700,
        charge: 0,
        isSatisfied: false,
        name: 'Violet Sensor',
      },
    ],
    obstacles: [
      {
        id: 1,
        points: [v2(500, 360), v2(540, 360), v2(540, 420), v2(500, 420)],
      },
    ],
  },
];
